### ISSUE TITLE
Constructor

### ISSUE THREAD

**Issue by TheAmberlamps** [CristobalSalazar/proj2#21]
A constructor using handlebars to populate our index page with music stored in our database.

**Comment by TheAmberlamps** [comment]
I can't quite figure out what's wrong with my code; it's a combination of not knowing where to register partials, and Handlebars not understanding my syntax *or* throwing any errors.

**Comment by CristobalSalazar** [comment]
I’ll take a look at it once we’re in class 🙂

**Comment by CristobalSalazar** [comment]
Push it to a branch so I can take a look

**Comment by TheAmberlamps** [comment]
we all good
